spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

aws:
  region: 리전
  access_key: [iam s3-user 엑세스 키]
  secret_key: [iam s3-user 시크릿 키]
  bucket: 버킷명
  cloud_front:
    domain: 클라우드프론트 도메인
    default-profile-image-key: "default-profile.png" # s3에 올려둔 기본 이미지 경로



jwt:
  secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
