spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

aws:
  region: ap-northeast-2
  access_key: [iam s3-user 엑세스 키]
  secret_key: [iam s3-user 시크릿 키]
  bucket: my-second-bucket-sh0405
  cloud_front:
    domain: d2tdzj50nwjpjq.cloudfront.net
    default-profile-image-key: "default-profile.png" # s3에 올려둔 기본 이미지 경로



jwt:
  secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
