spring:
  jpa:
    hibernate:
      ddl-auto: validate   # 개발 중에는 create / create-drop / update 중 선택
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
  profiles:
    include: secret

logging:
  level:
    org.hibernate.SQL: debug
