spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # 개발 중에는 create / create-drop / update 중 선택
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

aws:
  region:
  access_key:
  secret_key:
  bucket:
  cloud_front:
    domain:
    default-profile-image-key: "default-profile.png" # s3에 올려둔 기본 이미지 경로

jwt:
  secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb